#
# check-pr.yml
<<<<<<< HEAD
# Add a comment to the PR if it's directed to a release branch
#

name: Check PR
=======
# Close PRs directed at release branches
#

name: PR Bad Target
>>>>>>> ba2939b1dc55c04f879ce96e9af990287b4468d2

on:
  pull_request:
    branches:
    - 1.0.x
    - 1.1.x
    - 2.0.x

jobs:
<<<<<<< HEAD
  check_pr:
=======
  bad_target:
    name: PR Bad Target
    if: github.repository == 'MarlinFirmware/Marlin'
>>>>>>> ba2939b1dc55c04f879ce96e9af990287b4468d2

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - name: Comment on PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "<p>Thanks for your contribution! \
              Unfortunately we can't accept PRs directed at release branches. \
              We make patches to the bugfix branches and only later do we push them out as releases. \
              Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.</p> \
              <p>It may help to set your fork's default branch to `bugfix-2.0.x`.</p> \
              <p>See <a href='http://marlinfw.org/docs/development/getting_started_pull_requests.html' target='_blank'>this page</a> for full instructions.</p>"
=======
    - uses: peter-evans/close-pull@v1
      with:
        delete-branch: false
        comment: >
          Thanks for your contribution! Unfortunately we can't accept PRs directed at release branches. We make patches to the bugfix branches and only later do we push them out as releases.

          Please redo this PR starting with the `bugfix-2.0.x` branch and be careful to target `bugfix-2.0.x` when resubmitting the PR.

          It may help to set your fork's default branch to `bugfix-2.0.x`.

          See [this page](http://marlinfw.org/docs/development/getting_started_pull_requests.html) for full instructions.
>>>>>>> ba2939b1dc55c04f879ce96e9af990287b4468d2
